app:
  outbound:
    org: http://localhost:8080/organization
    lead: http://localhost:8080/lead
    admission: http://localhost:8080/admission
    master: http://localhost:8080/master

setup:
  config:
    - org: ../config/org_setup_config.yml
    - student: ../config/stuent_setup_config.yml
    - master: ../config/master_setup_config.yml